name: Build Cordova Android App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java (JDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Cordova and Android SDK
        run: |
          npm install -g cordova
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0"
          
      - name: Build Android App Bundle (AAB)
        run: |
          cordova platform add android
          cordova build android --release -- --bundle=aab

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-aab
          path: platforms/android/app/build/outputs/bundle/release/app-release.aab
